---
- name: Удаление Zabbix Agent
  apt:
    name: zabbix-agent
    state: absent
    
- name: Проверка, установлен ли Zabbix Agent 2
  stat:
    path: /usr/sbin/zabbix_agent2
  register: zabbix_agent2_installed

- name: Скачать пакет репозитория Zabbix
  get_url:
    url: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_6.4+ubuntu20.04_all.deb
    dest: /tmp/zabbix-release_latest_6.4+ubuntu20.04_all.deb
  when: not zabbix_agent2_installed.stat.exists

- name: Установить пакет репозитория Zabbix с помощью dpkg
  command: dpkg -i /tmp/zabbix-release_latest_6.4+ubuntu20.04_all.deb
  when: not zabbix_agent2_installed.stat.exists

- name: Обновить кеш пакетов
  apt:
    update_cache: yes
  when: not zabbix_agent2_installed.stat.exists

- name: Установить Zabbix Agent 2
  apt:
    name: zabbix-agent2
    state: present
  when: not zabbix_agent2_installed.stat.exists

- name: Настроить Zabbix Agent 2
  template:
    src: zabbix_agent2.conf.j2
    dest: "{{ zabbix_agent_config }}"
  notify: Перезапустить Zabbix Agent 2

- name: Получить токен аутентификации Zabbix API
  uri:
    url: "http://{{zabbix_server }}/api_jsonrpc.php"
    method: POST
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "user.login"
      params:
        user: "{{ admin_user }}"
        password: "{{ admin_pass }}"
      id: 1
    return_content: yes
  register: auth_result

- name: Добавить хост на Zabbix Server
  uri:
    url: "http://{{zabbix_server }}/api_jsonrpc.php"
    method: POST
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "host.create"
      params:
        host: "{{ inventory_hostname }}"
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "{{ ansible_host }}"
            dns: ""
            port: "10050"
        groups:
          - groupid: "{{ groupid }}"  
        templates:
          - templateid: "{{ templateid }}"  # ID шаблона, который применяется к хосту
      auth: "{{ auth_result.json.result }}"
      id: 1
    return_content: yes
  register: host_create_result

- name: Вывести результат добавления хоста
  debug:
    var: host_create_result.json